[package]
name = "simple-middleware"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "General purpose middleware crate"
keywords = ["webdev", "web", "middleware"]
categories = ["asynchronous", "web-programming"]
rust-version = "1.78"

[dependencies]
async-trait = "0.1.68"
futures = "0.3.27"
tokio = { version = "1.28.2", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1.28.2", features = ["full"] }
uuid = { version = "1.3.4", features = ["v4"] }
